name: SugNet

channels:
  - conda-forge
  - default

dependencies:
  - python
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - flake8
  - ipykernel
  - jupyter
  - notebook
  - xarray
  - netcdf4
  - openpyxl
  - shap
  - pip
  - mne
  - mne-bids  
