name: otka

dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - vtk
  - pyqt
  - qt
  - flake8
  - ipykernel
  - jupyter
  - notebook
  - xarray
  - netcdf4
  - dask
  - openpyxl
  - shap
  - pip:
    - mne
    - mne-connectivity
    - autoreject
    - mne-bids
    - pyvista
    - ipyvtklink
    - umap
    - scikit-optimize
    - autokeras
    - fooof
    - neurodsp
